<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.0.0-dev</Version>
    <ApplicationIcon>logo_v.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="itext7" Version="7.2.5" />
    <PackageReference Include="itext7.bouncy-castle-adapter" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="logo.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="logo_v.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <PropertyGroup>
    <ApiKey Condition="'$(ApiKey)' == ''">$([System.Environment]::GetEnvironmentVariable('BULK_PDF_SIGNER_API_KEY'))</ApiKey>
  </PropertyGroup>
  <ItemGroup Condition="'$(ApiKey)' != ''">
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>ApiKey</_Parameter1>
      <_Parameter2>$(ApiKey)</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>

</Project>